// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htvburitplikfnpwxpvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0dmJ1cml0cGxpa2ZucHd4cHZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MzY2MzQsImV4cCI6MjA2OTUxMjYzNH0.o6ddAT08rmro2bpCZ0DSTyPZqRHEbRQI1HzMgXPMH78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});